parameters:
  rounds: 5
  roundTime: 6000
  giveFood: 16
block-list:
  - ACACIA_WOOD
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - AZURE_BLUET
  - BAMBOO
  - BARREL
  - BEDROCK
  - BELL
  - BIRCH_BUTTON
  - BIRCH_DOOR
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_PRESSURE_PLATE
  - BIRCH_SAPLING
  - BIRCH_SIGN
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_TRAPDOOR
  - BIRCH_WOOD
  - 0.5 BLACK_BANNER
  - 0.5 BLACK_BED
  - 0.5 BLACK_CARPET
  - 0.5 BLACK_CONCRETE
  - 0.5 BLACK_CONCRETE_POWDER
  - 0.5 BLACK_GLAZED_TERRACOTTA
  - 0.5 BLACK_STAINED_GLASS
  - 0.5 BLACK_STAINED_GLASS_PANE
  - 0.5 BLACK_TERRACOTTA
  - 0.5 BLACK_WOOL
  - BLAST_FURNACE
  - BLUE_BANNER
  - 0.5 BLUE_BED
  - 0.5 BLUE_CARPET
  - 0.5 BLUE_CONCRETE
  - 0.5 BLUE_CONCRETE_POWDER
  - 0.5 BLUE_GLAZED_TERRACOTTA
  - 0.5 BLUE_ORCHID
  - 0.5 BLUE_STAINED_GLASS
  - 0.5 BLUE_STAINED_GLASS_PANE
  - 0.5 BLUE_TERRACOTTA
  - 0.5 BLUE_WOOL
  - BONE_BLOCK
  - BOOKSHELF
  - 0.2 BREWING_STAND
  - BRICKS
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - 0.7 BROWN_MUSHROOM
  - 0.7 BROWN_MUSHROOM_BLOCK
  - CACTUS
  - CAKE
  - CAMPFIRE
  - CARTOGRAPHY_TABLE
  - CARVED_PUMPKIN
  - CAULDRON
  - CHEST
  - CHISELED_QUARTZ_BLOCK
  - CHISELED_RED_SANDSTONE
  - CHISELED_SANDSTONE
  - CLAY
  - 0.5 COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COBWEB
  - COMPARATOR
  - COMPOSTER
  - CORNFLOWER
  - CRACKED_STONE_BRICKS
  - CRAFTING_TABLE
  - CUT_RED_SANDSTONE
  - CUT_RED_SANDSTONE_SLAB
  - CUT_SANDSTONE
  - CUT_SANDSTONE_SLAB
  - DANDELION
  - 0.7 DARK_OAK_BUTTON
  - 0.7 DARK_OAK_DOOR
  - 0.7 DARK_OAK_FENCE
  - 0.7 DARK_OAK_FENCE_GATE
  - 0.7 DARK_OAK_LEAVES
  - 0.7 DARK_OAK_LOG
  - 0.7 DARK_OAK_PLANKS
  - 0.7 DARK_OAK_PRESSURE_PLATE
  - 0.7 DARK_OAK_SAPLING
  - 0.7 DARK_OAK_SIGN
  - 0.7 DARK_OAK_SLAB
  - 0.7 DARK_OAK_STAIRS
  - 0.7 DARK_OAK_TRAPDOOR
  - 0.7 DARK_OAK_WOOD
  - DEAD_BUSH
  - 0.4 DIAMOND_ORE
  - DIORITE
  - DIORITE_SLAB
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - 0.6 DISPENSER
  - DRIED_KELP_BLOCK
  - 0.6 DROPPER
  - 0.2 EMERALD_ORE
  - FARMLAND
  - FERN
  - FIRE
  - FLETCHING_TABLE
  - FLOWER_POT
  - FURNACE
  - GLASS
  - GLASS_PANE
  - 0.5 GLOWSTONE
  - 0.2 GOLD_BLOCK
  - 0.4 GOLD_ORE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS
  - GRASS_BLOCK
  - GRASS_PATH
  - GRAVEL
  - 0.5 GREEN_BANNER
  - 0.5 GREEN_BED
  - 0.5 GREEN_CARPET
  - 0.5 GREEN_CONCRETE
  - 0.5 GREEN_CONCRETE_POWDER
  - 0.5 GREEN_GLAZED_TERRACOTTA
  - 0.5 GREEN_STAINED_GLASS
  - 0.5 GREEN_STAINED_GLASS_PANE
  - 0.5 GREEN_TERRACOTTA
  - 0.5 GREEN_WOOL
  - GRINDSTONE
  - HAY_BLOCK
  - ICE
  - 0.3 IRON_BARS
  - 0.3 IRON_BLOCK
  - 0.3 IRON_DOOR
  - IRON_ORE
  - 0.3 IRON_TRAPDOOR
  - JACK_O_LANTERN
  - LADDER
  - LANTERN
  - 0.4 LAPIS_ORE
  - LARGE_FERN
  - LAVA
  - LECTERN
  - LEVER
  - LILAC
  - LILY_PAD
  - LOOM
  - 0.5 MAGENTA_BANNER
  - 0.5 MAGENTA_BED
  - 0.5 MAGENTA_CARPET
  - 0.5 MAGENTA_CONCRETE
  - 0.5 MAGENTA_CONCRETE_POWDER
  - 0.5 MAGENTA_GLAZED_TERRACOTTA
  - 0.5 MAGENTA_STAINED_GLASS
  - 0.5 MAGENTA_STAINED_GLASS_PANE
  - 0.5 MAGENTA_TERRACOTTA
  - 0.5 MAGENTA_WOOL
  - 0.5 MAGMA_BLOCK
  - MELON
  - 0.5 NETHERRACK
  - 0.5 NETHER_BRICKS
  - 0.5 NETHER_PORTAL
  - 0.5 NETHER_QUARTZ_ORE
  - 0.5 NETHER_WART
  - NOTE_BLOCK
  - OAK_BUTTON
  - OAK_DOOR
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_PRESSURE_PLATE
  - OAK_SAPLING
  - OAK_SIGN
  - OAK_SLAB
  - OAK_STAIRS
  - OAK_TRAPDOOR
  - OAK_WOOD
  - 0.7 OBSIDIAN
  - 0.5 ORANGE_BANNER
  - 0.5 ORANGE_BED
  - 0.5 ORANGE_CARPET
  - 0.5 ORANGE_CONCRETE
  - 0.5 ORANGE_CONCRETE_POWDER
  - 0.5 ORANGE_GLAZED_TERRACOTTA
  - 0.5 ORANGE_STAINED_GLASS
  - 0.5 ORANGE_STAINED_GLASS_PANE
  - 0.5 ORANGE_TERRACOTTA
  - 0.5 ORANGE_TULIP
  - 0.5 ORANGE_WOOL
  - OXEYE_DAISY
  - PEONY
  - POLISHED_ANDESITE
  - POLISHED_ANDESITE_SLAB
  - POLISHED_ANDESITE_STAIRS
  - POLISHED_DIORITE
  - POLISHED_DIORITE_SLAB
  - POLISHED_DIORITE_STAIRS
  - POLISHED_GRANITE
  - POLISHED_GRANITE_SLAB
  - POLISHED_GRANITE_STAIRS
  - POPPY
  - 0.5 POTTED_BLUE_ORCHID
  - 0.7 POTTED_BROWN_MUSHROOM
  - 0.5 POTTED_CACTUS
  - 0.5 POTTED_CORNFLOWER
  - 0.5 POTTED_DANDELION
  - 0.5 POTTED_OAK_SAPLING
  - 0.5 POTTED_ORANGE_TULIP
  - 0.5 POTTED_POPPY
  - 0.5 POTTED_RED_MUSHROOM
  - 0.5 POTTED_RED_TULIP
  - 0.5 POTTED_WHITE_TULIP
  - 0.3 POWERED_RAIL
  - PUMPKIN
  - 0.5 QUARTZ_BLOCK
  - 0.5 QUARTZ_SLAB
  - 0.5 QUARTZ_STAIRS
  - 0.6 RAIL
  - 0.3 REDSTONE_LAMP
  - 0.5 REDSTONE_ORE
  - REDSTONE_TORCH
  - REDSTONE_WIRE
  - 0.5 RED_BANNER
  - 0.5 RED_BED
  - 0.5 RED_CARPET
  - 0.5 RED_CONCRETE
  - 0.5 RED_CONCRETE_POWDER
  - 0.5 RED_GLAZED_TERRACOTTA
  - 0.7 RED_MUSHROOM
  - 0.7 RED_MUSHROOM_BLOCK
  - 0.4 RED_SAND
  - 0.4 RED_SANDSTONE
  - 0.4 RED_SANDSTONE_SLAB
  - 0.4 RED_SANDSTONE_STAIRS
  - 0.4 RED_SANDSTONE_WALL
  - 0.5 RED_STAINED_GLASS
  - 0.5 RED_STAINED_GLASS_PANE
  - 0.5 RED_TERRACOTTA
  - 0.5 RED_TULIP
  - 0.5 RED_WOOL
  - 0.5 REPEATER
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SCAFFOLDING
  - 0.5 SEA_LANTERN
  - SEA_PICKLE
  - 0.7 SMITHING_TABLE
  - SMOKER
  - 0.5 SMOOTH_QUARTZ
  - 0.5 SMOOTH_QUARTZ_SLAB
  - 0.5 SMOOTH_QUARTZ_STAIRS
  - SNOW
  - SNOW_BLOCK
  - 0.5 SOUL_SAND
  - 0.2 SPONGE
  - SPRUCE_BUTTON
  - SPRUCE_DOOR
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_PRESSURE_PLATE
  - SPRUCE_SAPLING
  - SPRUCE_SIGN
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_TRAPDOOR
  - SPRUCE_WALL_SIGN
  - SPRUCE_WOOD
  - STONE
  - STONECUTTER
  - STONE_BRICKS
  - STONE_BRICK_SLAB
  - STONE_BRICK_STAIRS
  - STONE_BRICK_WALL
  - STONE_BUTTON
  - STONE_PRESSURE_PLATE
  - STONE_SLAB
  - STONE_STAIRS
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TALL_GRASS
  - TERRACOTTA
  - TNT
  - TORCH
  - 0.7 TRAPPED_CHEST
  - TRIPWIRE_HOOK
  - 0.5 VINE
  - WATER
  - 0.5 WHITE_BANNER
  - 0.5 WHITE_BED
  - 0.5 WHITE_CARPET
  - 0.5 WHITE_CONCRETE
  - 0.5 WHITE_CONCRETE_POWDER
  - 0.5 WHITE_GLAZED_TERRACOTTA
  - 0.5 WHITE_STAINED_GLASS
  - 0.5 WHITE_STAINED_GLASS_PANE
  - 0.5 WHITE_TERRACOTTA
  - 0.5 WHITE_TULIP
  - 0.5 WHITE_WOOL
  - 0.5 YELLOW_BANNER
  - 0.5 YELLOW_BED
  - 0.5 YELLOW_CARPET
  - 0.5 YELLOW_CONCRETE
  - 0.5 YELLOW_CONCRETE_POWDER
  - 0.5 YELLOW_GLAZED_TERRACOTTA
  - 0.5 YELLOW_STAINED_GLASS
  - 0.5 YELLOW_STAINED_GLASS_PANE
  - 0.5 YELLOW_TERRACOTTA
  - 0.5 YELLOW_WOOL
